bt_navigator:
  ros__parameters:
    use_sim_time: true
    global_frame: odom
    robot_base_frame: base_link
    odom_frame: odom


controller_server:
  ros__parameters:
    use_sim_time: true
    controller_frequency: 20.0
    cmd_vel_topic: "cmd_vel_nav"

    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "nav2_mppi_controller::MPPIController"

      # Timing / rollout
      time_steps: 56
      model_dt: 0.05
      batch_size: 1000
      iteration_count: 1 # controls how many iterations of paths it explores

      # Limits for pavbot
      vx_max: 0.4 # 3.35 mph
      vx_min: -0.2 # can back up now
      wz_max: 1.0

      # Noise (bigger = explores more)
      vx_std: 0.35
      wz_std: 0.8

      # Critics = how it scores trajectories
      critics: ["ConstraintCritic", "ObstaclesCritic", "PathAlignCritic", "PathFollowCritic", "GoalCritic"]

      ConstraintCritic:
        enabled: true
        cost_power: 1
        cost_weight: 4.0

      ObstaclesCritic:
        enabled: true
        cost_power: 1
        repulsion_weight: 22.0 # more keep away
        critical_weight: 170.0
        collision_cost: 100000.0
        collision_margin_distance: 0.1

      # How hard do I follow centerline???
      PathAlignCritic:
        enabled: true
        weight: 3.0

      PathFollowCritic:
        enabled: true
        weight: 4.0

      GoalCritic:
        enabled: true
        weight: 6.0


velocity_smoother:
  ros__parameters:
    use_sim_time: true

    # Smoother subscribes to controller output...
    input_topic: "cmd_vel_nav"
    # publishes to the robot
    output_topic: "cmd_vel"

    smoothing_frequency: 30.0
    feedback: "OPEN_LOOP"

    # Limits (tune later)
    max_velocity: [1.9, 0.0, 1.9]
    min_velocity: [-0.1, 0.0, -1.5]
    max_accel: [1.0, 0.0, 2.0]
    max_decel: [-1.0, 0.0, -2.0]
    odom_topic: "/odom"
    odom_duration: 0.1
    deadband_velocity: [0.0, 0.0, 0.0]
    velocity_timeout: 1.0

planner_server:
  ros__parameters:
    use_sim_time: true
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.5
      use_astar: false
      allow_unknown: true

behavior_server:
  ros__parameters:
    use_sim_time: true
    global_frame: odom
    robot_base_frame: base_link
    odom_frame: odom
    behavior_plugins: ["spin", "backup", "drive_on_heading", "wait"]
    spin:
      plugin: "nav2_behaviors/Spin"
    backup:
      plugin: "nav2_behaviors/BackUp"
    drive_on_heading:
      plugin: "nav2_behaviors/DriveOnHeading"
    wait:
      plugin: "nav2_behaviors/Wait"

local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 10.0
      publish_frequency: 5.0
      footprint: "[[-0.56, -0.335], [0.56, -0.335], [0.56, 0.335], [-0.56, 0.335]]"
      footprint_padding: 0.03
      always_send_full_costmap: true
      transform_tolerance: 0.2
      use_sim_time: true
      global_frame: odom
      robot_base_frame: base_link
      rolling_window: true
      width: 10
      height: 10
      resolution: 0.05

      plugins: ["obstacle_layer", "inflation_layer"]

      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: true
        observation_sources: scan pothole_cloud
        combination_method: 1
        track_unknown_space: false
        footprint_clearing_enabled: false

        scan:
          topic: /scan
          data_type: "LaserScan"
          marking: true
          clearing: true
          obstacle_max_range: 12.0
          obstacle_min_range: 0.0
          raytrace_max_range: 15.0
          raytrace_min_range: 0.0
          min_obstacle_height: 0.0
          max_obstacle_height: 1.5
          inf_is_valid: false
          observation_persistence: 0.0
          expected_update_rate: 10.0

        pothole_cloud:
          topic: /potholes/points
          data_type: "PointCloud2"
          marking: true
          clearing: false
          obstacle_max_range: 10.0
          obstacle_min_range: 0.0
          raytrace_max_range: 0.0
          raytrace_min_range: 0.0
          min_obstacle_height: -1.0
          max_obstacle_height: 1.0
          inf_is_valid: false
          observation_persistence: 3.00
          expected_update_rate: 10.0

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        enabled: true
        inflation_radius: 1.0
        cost_scaling_factor: 9.0


global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: true
      global_frame: odom
      robot_base_frame: base_link
      rolling_window: true
      width: 20
      height: 20
      resolution: 0.05
      update_frequency: 2.0
      publish_frequency: 1.0
      footprint: "[[-0.5, -0.35], [0.5, -0.35], [0.5, 0.35], [-0.5, 0.35]]" # more accurate than huge radius
      footprint_padding: 0.03
# (and remove robot_radius)
      #robot_radius: 0.45
      plugins: ["lidar_obstacles","inflation_layer"]

      transform_tolerance: 0.2

      lidar_obstacles:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: true
        observation_sources: scan
        combination_method: 1
        track_unknown_space: false

        scan:
          topic: /scan
          data_type: "LaserScan"
          marking: true
          clearing: true
          obstacle_range: 15.0
          raytrace_range: 18.0
          min_obstacle_height: 0.0
          max_obstacle_height: 1.5
          observation_persistence: 0.2
          expected_update_rate: 10.0
          inf_is_valid: false

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.45
        cost_scaling_factor: 6.0




lifecycle_manager_navigation:
  ros__parameters:
    use_sim_time: true
    autostart: true
    node_names:
      - controller_server
      - planner_server
      - behavior_server
      - local_costmap
      - global_costmap
      - bt_navigator
      - velocity_smoother